--SHOW SUBJECT
SELECT * FROM SUBJECT;

--SHOW TOPIC
SELECT * FROM TOPIC;

--SHOW TEACHER
SELECT * FROM TEACHER;

--SHOW STUDENT
SELECT * FROM STUDENT;

--SHOW QUESTION_TYPE
SELECT * FROM QUESTION_TYPE;

--SHOW QUESTION
SELECT * FROM QUESTION
--WHERE TOPIC_NAME = 'Music History';
ORDER BY QUESTION_ID


--SHOW QUESTION
SELECT TOPIC_NAME,COUNT(*) FROM QUESTION
-- WHERE TOPIC_NAME = 'Probability Theory'
GROUP BY TOPIC_NAME
ORDER BY COUNT(*) DESC
--SHOW QUESTION_SET
SELECT * FROM QUESTION_SET
ORDER BY QUESTION_SET_ID;

 -- Generate the next sequence value for Question_Set_ID
    SELECT question_set_sequence.NEXTVAL FROM DUAL;



INSERT INTO QUESTION_SET (QUESTION_SET_NAME, ACCESSIBILITY_LEVEL, TEACHER_ID, NO_OF_QUESTIONS, TOTAL_MARKS, LEVEL_NAME)
VALUES ('QUESTION SET 22', '1', 1, 20, 200, 'Undergraduate');

--SHOW QUESTION_SET_QUESTION
SELECT * FROM QUESTION_SET_QUESTION
wHERE QUESTION_SET_ID =12
ORDER BY QUESTION_SET_ID;

--SHOW QUESTION
SELECT QUESTION_ID,TOPIC_NAME FROM QUESTION
WHERE TOPIC_NAME in ('Music History','Ecology','Cell Biology')
GROUP BY TOPIC_NAME


--SHOW EXAM
SELECT * FROM EXAM;

--SHOW EXAM_PARTICIPATION
SELECT * FROM EXAM_PARTICIPATION;

--SHOW EXAM_ANSWER
SELECT * FROM EXAM_ANSWER;


select To_char(REGISTERED_DATE,'HH:MI AM "on" Day-DD-Month-YYYY') from student;

-- INSERT KORSI 1ta DATA
delete from QUESTION WHERE QUESTION_ID = 227; -- SHOWS ORA-02292: integrity constraint (DELETE CASCADE KORA LAGBE)
UPDATE QUESTION set QUESTION_BODY ='MOther' where QUESTION_ID = 227;

--SHOW QUESTION_LOG
SELECT * FROM QUESTION_LOG;

INSERT INTO QUESTION_SET (QUESTION_SET_NAME, ACCESSIBILITY_LEVEL, TEACHER_ID, NO_OF_QUESTIONS, TOTAL_MARKS, LEVEL_NAME)
VALUES ('QUESTION SET 4', '1', 1, 20, 200, 'Undergraduate');

--SHOW QUESTION_SET_LOG
SELECT * FROM QUESTION_SET_LOG;

UPDATE QUESTION_SET set QUESTION_SET_NAME ='MOther' where QUESTION_SET_ID = 4;