DELETE FROM EXAM_PARTICIPATION;

INSERT INTO EXAM_PARTICIPATION(STUDENT_ID,EXAM_ID,FEEDBACK)
VALUES (1,1,'THE TEST WAS A BIT HARD BUT ENJOYED IT.');

INSERT INTO EXAM_PARTICIPATION(STUDENT_ID,EXAM_ID,FEEDBACK)
VALUES (2,1,'THE EXAM WAS A BIT TRICKY.');

--SHOW EXAM_PARTICIPATION
SELECT * FROM EXAM_PARTICIPATION;

--SHOW EXAM_ANSWER
SELECT * FROM EXAM_ANSWER
ORDER BY STUDENT_ID;