--SHOW SUBJECT
SELECT * FROM SUBJECT;

--SHOW TOPIC
SELECT * FROM TOPIC;

--SHOW TEACHER
SELECT * FROM TEACHER;

--SHOW STUDENT
SELECT * FROM STUDENT;

--SHOW QUESTION_TYPE
SELECT * FROM QUESTION_TYPE;

--SHOW QUESTION
SELECT * FROM QUESTION
ORDER BY QUESTION_ID;

--SHOW QUESTION SET
SELECT * FROM QUESTION_SET;

--SHOW QUESTION SET QUESTION
SELECT * FROM QUESTION_SET_QUESTION;

--SHOW EXAM
SELECT * FROM EXAM;

