INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS,REGISTERED_DATE)
VALUES (1, 'admin123456', 'H M Aktaruzzaman', 'Mukdho', 'mukdho.zaman@gmail.com', 1, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass1', 'John', 'Doe', 'john.doe@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass2', 'Alice', 'Smith', 'alice.smith@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass3', 'Michael', 'Johnson', 'michael.johnson@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass4', 'Emily', 'Brown', 'emily.brown@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass5', 'William', 'Jones', 'william.jones@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass6', 'Emma', 'Davis', 'emma.davis@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass7', 'James', 'Wilson', 'james.wilson@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass8', 'Olivia', 'Martinez', 'olivia.martinez@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass9', 'Benjamin', 'Anderson', 'benjamin.anderson@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass10', 'Sophia', 'Taylor', 'sophia.taylor@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass11', 'Alexander', 'Thomas', 'alexander.thomas@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass12', 'Charlotte', 'White', 'charlotte.white@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass13', 'Daniel', 'Harris', 'daniel.harris@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass14', 'Ava', 'Martin', 'ava.martin@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass15', 'Mia', 'Thompson', 'mia.thompson@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass16', 'Logan', 'Garcia', 'logan.garcia@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass17', 'Evelyn', 'Robinson', 'evelyn.robinson@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass18', 'William', 'Stewart', 'william.stewart@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass19', 'Harper', 'Scott', 'harper.scott@example.com', 0, SYSDATE);

INSERT INTO TEACHER (IS_ADMIN, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, APPROVAL_STATUS, REGISTERED_DATE)
VALUES (0, 'teacherpass20', 'Evelyn', 'Young', 'evelyn.young@example.com', 0, SYSDATE);
