INSERT INTO QUESTION_TYPE (TYPE_NAME, TYPE_DESCRIPTION)
VALUES ('MCQ', 'Multiple Choice Question');

INSERT INTO QUESTION_TYPE (TYPE_NAME, TYPE_DESCRIPTION)
VALUES ('FIB', 'Fill in the Blank');

INSERT INTO QUESTION_TYPE (TYPE_NAME, TYPE_DESCRIPTION)
VALUES ('TF', 'True or False');

