-- Insert demo data into EXAM table
INSERT INTO EXAM (EXAM_TYPE, SCHEDULED_BY, QUESTION_SET_ID, EXAM_TIME, EXAM_DURATION, LEVEL_NAME)
VALUES ('Scheduled', 1, 1, '2024-03-07 09:00:00', 20, 'Undergraduate');

INSERT INTO EXAM (EXAM_TYPE, SCHEDULED_BY, QUESTION_SET_ID, EXAM_TIME, EXAM_DURATION, LEVEL_NAME)
VALUES ('Scheduled', 1, 2, '2024-03-08 10:00:00', 20, 'Undergraduate');

INSERT INTO EXAM (EXAM_TYPE, SCHEDULED_BY, QUESTION_SET_ID, EXAM_TIME, EXAM_DURATION, LEVEL_NAME)
VALUES ('Scheduled', 1, 3, '2024-03-09 11:00:00', 20, 'Undergraduate');

--Add more INSERT statements as needed for additional demo data