INSERT INTO QUESTION_SET (QUESTION_SET_NAME, ACCESSIBILITY_LEVEL, TEACHER_ID, NO_OF_QUESTIONS, TOTAL_MARKS, LEVEL_NAME)
VALUES ('QUESTION SET 1', '1', 1, 20, 200, 'Undergraduate');

INSERT INTO QUESTION_SET (QUESTION_SET_NAME, ACCESSIBILITY_LEVEL, TEACHER_ID, NO_OF_QUESTIONS, TOTAL_MARKS, LEVEL_NAME)
VALUES ('QUESTION SET 2', '1', 1, 20, 200, 'Undergraduate');

INSERT INTO QUESTION_SET (QUESTION_SET_NAME, ACCESSIBILITY_LEVEL, TEACHER_ID, NO_OF_QUESTIONS, TOTAL_MARKS, LEVEL_NAME)
VALUES ('QUESTION SET 3', '1', 1, 20, 200, 'Undergraduate');

