
DELETE FROM EXAM_ANSWER;
--SHOW EXAM_ANSWER
SELECT * FROM EXAM_ANSWER;

-- Inserting sample answers for Mathematics MCQs
INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 1, 1, '3.1415');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 2, 1, '15');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 3, 1, '48');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 4, 1, '2.718');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 5, 1, '0.5');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 6, 1, '4');

-- Inserting sample answers for English Language MCQs
INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 7, 1, 'Harper Lee');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 8, 1, 'Enlightenment');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 9, 1, 'William Shakespeare');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 10, 1, 'Imagery');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 11, 1, 'George Orwell');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 12, 1, 'Romanticism');

-- Inserting sample answers for Chemistry MCQs
INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 13, 1, 'Au');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 14, 1, 'Helium');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 15, 1, 'H2O');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 16, 1, 'Chlorine');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 17, 1, 'Carbon dioxide');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 18, 1, 'NaCl');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 19, 1, 'Arsenic');

-- INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
-- VALUES (1, 20, 1, 'Methane');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (1, 20, 1, 'Ethane');

--DEMO DATA FOR STUDENT 2

-- Inserting sample answers for Mathematics MCQs
INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 1, 1, '3.1415');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 2, 1, '15');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 3, 1, '48');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 4, 1, '2.718');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 5, 1, '0.5');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 6, 1, '4');

-- Inserting sample answers for English Language MCQs
INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 7, 1, 'Harper Lee');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 8, 1, 'Enlightenment');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 9, 1, 'William Shakespeare');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 10, 1, 'Imagery');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 11, 1, 'George Orwell');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 12, 1, 'Romanticism');

-- Inserting sample answers for Chemistry MCQs
INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 13, 1, 'Au');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 14, 1, 'Nitrogen');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 15, 1, 'C2O');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 16, 1, 'Chlorine');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 17, 1, 'Carbon dioxide');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 18, 1, 'NaCl');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 19, 1, 'Arsenic');

-- INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
-- VALUES (2, 20, 1, 'Methane');

INSERT INTO EXAM_ANSWER (STUDENT_ID, QUESTION_ID, EXAM_ID, GIVEN_ANSWER)
VALUES (2, 20, 1, 'Ethane');


SELECT trigger_name, trigger_type, triggering_event, status
FROM user_triggers
WHERE trigger_name = 'UPDATE_IS_CORRECT';



select * from user_errors where type = 'TRIGGER' and name = 'UPDATE_IS_CORRECT'


SELECT *
FROM user_dependencies
WHERE name = 'UPDATE_IS_CORRECT';


