DROP PROCEDURE DELETE_QUESTION;

CREATE OR REPLACE PROCEDURE DELETE_QUESTION (QID NUMBER) AS
  IS_DELETED NUMBER;
BEGIN
  -- Check if the question exists and retrieve its current IS_DELETED value
  SELECT Q.IS_DELETED INTO IS_DELETED FROM QUESTION Q WHERE Q.QUESTION_ID = QID;

  -- If the question exists, update its IS_DELETED value to 1
  IF IS_DELETED IS NOT NULL THEN
    UPDATE QUESTION SET IS_DELETED = 1 WHERE QUESTION_ID = QID;
    DBMS_OUTPUT.PUT_LINE('Question with ID ' || QID || ' has been deleted.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Question with ID ' || QID || ' does not exist.');
  END IF;

EXCEPTION 
	WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('OTHER ERROR IN DELETE_QUESTION');
END;
/


BEGIN
  DELETE_QUESTION(1);
END;
/
