INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Mathematics', 'Mathematics involves the study of numbers, quantity, structure, and space.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('English Language', 'English Language studies involve the examination of literature, composition, and language structure.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Science', 'Science encompasses the study of the natural world, including biology, chemistry, and physics.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Social Studies', 'Social Studies explores human society, culture, and relationships.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('History', 'History investigates past events, societies, and civilizations.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Computer Science', 'Computer Science covers the study of algorithms, programming, and computer systems.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Physical Education', 'Physical Education focuses on physical fitness, sports, and exercise.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Art', 'Art involves the creation and appreciation of visual arts and design.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Music', 'Music studies encompass the theory, composition, and performance of music.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Foreign Language', 'Foreign Language studies involve learning languages other than one''s native language.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Geography', 'Geography examines the Earth''s landscapes, environments, and spatial relationships.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Economics', 'Economics studies the production, distribution, and consumption of goods and services.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Political Science', 'Political Science explores government, political systems, and political behavior.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Psychology', 'Psychology investigates human behavior, cognition, and mental processes.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Sociology', 'Sociology examines social institutions, groups, and interactions.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Chemistry', 'Chemistry studies the composition, properties, and reactions of substances.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Biology', 'Biology focuses on the study of living organisms and their interactions.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Physics', 'Physics explores the fundamental principles governing matter, energy, and motion.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Literature', 'Literature encompasses the study and analysis of written works, including novels, poems, and plays.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Algebra', 'Algebra involves the study of mathematical symbols and the rules for manipulating these symbols.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('World History', 'World History examines historical events and developments on a global scale.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Environmental Science', 'Environmental Science studies the natural environment and its interactions with human societies.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Business Studies', 'Business Studies cover various aspects of business management, finance, and entrepreneurship.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Physical Science', 'Physical Science explores the principles of physics and chemistry.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Calculus', 'Calculus involves the study of rates of change and accumulation.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('American History', 'American History focuses on historical events and developments within the United States.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('European History', 'European History examines historical events and developments in Europe.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Statistics', 'Statistics involves the collection, analysis, interpretation, and presentation of data.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Anthropology', 'Anthropology studies human societies, cultures, and evolution.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Ethics', 'Ethics explores moral principles and values governing human behavior.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Philosophy', 'Philosophy examines fundamental questions about existence, knowledge, values, reason, mind, and language.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Health Education', 'Health Education covers topics related to physical and mental health, wellness, and disease prevention.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Astronomy', 'Astronomy studies celestial objects, space, and the universe as a whole.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Literacy', 'Literacy focuses on reading, writing, and communication skills development.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Coding', 'Coding involves the creation and implementation of computer programs.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Digital Media', 'Digital Media covers the creation, editing, and distribution of multimedia content.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Engineering', 'Engineering studies the design, construction, and operation of systems, structures, and machines.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Law', 'Law involves the study of legal principles, systems, and practices.');
INSERT INTO SUBJECT (SUBJECT_NAME, SUBJECT_DESCRIPTION) VALUES ('Cultural Studies', 'Cultural Studies explore cultural practices, beliefs, and identities within societies.');
