CREATE OR REPLACE TRIGGER question_log_trigger
AFTER INSERT OR UPDATE OR DELETE ON QUESTION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO QUESTION_LOG (TEACHER_ID, QUESTION_ID, ACTION)
        VALUES (:NEW.TEACHER_ID, :NEW.QUESTION_ID, 'INSERT');
    ELSIF UPDATING THEN
        INSERT INTO QUESTION_LOG (TEACHER_ID, QUESTION_ID, ACTION)
        VALUES (:NEW.TEACHER_ID, :OLD.QUESTION_ID, 'UPDATE');
    ELSIF DELETING THEN
        INSERT INTO QUESTION_LOG (TEACHER_ID, QUESTION_ID, ACTION)
        VALUES (:OLD.TEACHER_ID, :OLD.QUESTION_ID, 'DELETE');
    END IF;
END;
/
