CREATE OR REPLACE TRIGGER student_login_trigger
AFTER INSERT ON STUDENT_LOG
FOR EACH ROW
BEGIN
    UPDATE STUDENT_LOG
    SET LOGIN_TIME = SYSTIMESTAMP
    WHERE STUDENT_ID = :NEW.STUDENT_ID AND LOGOUT_TIME IS NULL;
END;
/

CREATE OR REPLACE TRIGGER student_logout_trigger
BEFORE UPDATE ON STUDENT_LOG
FOR EACH ROW
BEGIN
    IF :NEW.LOGOUT_TIME IS NOT NULL THEN
        UPDATE STUDENT_LOG
        SET LOGOUT_TIME = SYSTIMESTAMP
        WHERE STUDENT_ID = :NEW.STUDENT_ID AND LOGIN_TIME = :NEW.LOGIN_TIME;
    END IF;
END;
/
